### ISSUE TITLE
[Intro to iOS] Prework - Review my app

### ISSUE THREAD

**Issue by DGh0st** [DGh0st/Tipster#1]
My app is complete, please review. /cc @codepathreview

**Comment by DGh0st** [comment]
I have added UI Animations and Locale-specific currency symbol. I have also moved the preferences from the settings application to my application (SettingsViewController). My app is updated, please review. /cc @codepathreview

**Comment by DGh0st** [comment]
Fixed a bug with settings changed through SettingsViewController did not retake effect on application restart. The code has this issue fixed but the video walk through does not display this. I hope that does not cause issues in the review process. /cc @codepathreview

**Comment by chieger** [comment]
A truly AMAZING submission Deep! Way to go above and beyond! This is exactly the kind of work ethic, dedication and creativity we are looking for in CodePath students!

This pre-work is a preview of our weekly project process. Generally, weekly projects take about 5 hours to complete the required features and an additional 5 hours to complete the optional features. In general, we've seen that the more hours you log, the quicker you improve your proficiency with iOS.

The purpose of this project was to begin to explore Xcode and to get a broad overview of iOS development using Swift. For example, in this project, we explored the following concepts:

Code styling in Swift. You can find some code styling guides here:

[Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
[Github Swift Style Guide](https://github.com/github/swift-style-guide)
- Views are created in Storyboard, Interface Builder, or programmatically, but they have the same goal: instantiate, initialize, and layout view objects. We use IBOutlets to give names to view objects, similar to giving unique ids to divs in HTML.
- We registered for touch events, which can be done programmatically or via IBActions.
- We explored NSUserDefaults, one of the four persistence strategies in iOS.
- View controllers have a set of methods that are called when it loads, appears, or disappears. These are called view controller lifecycle methods.

Do your views look good on iPhone 4, 5, and 6? We will cover in class how to use Auto Layout to robustly design your views for different screen sizes and OS versions.

After this assignment, you should understand the purpose of IBOutlets and IBActions as well as the basics of designing views and programmatically interacting with the views from the controller.

Acceptance emails will be sent out during the first week of January.

Charlie Hieger
CodePath
